-- Active: 1735250242590@@127.0.0.1@3306@datag3
-- CREAR TABLA
CREATE TABLE alumno(  
    id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nro_documento VARCHAR(10) NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    emial VARCHAR(100)
);

-- MODIFICAR TABLA
ALTER TABLE alumno
ADD COLUMN nota INT DEFAULT 0;

-- ELIMINAR TABLA
DROP TABLE alumno;

